# Generated by Django 5.0.6 on 2024-06-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_service.specialty'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
