# Generated by Django 5.0.6 on 2024-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
